const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('auto_trader/static/long-term.js', 'utf8');
const nodes = new Map();
const $ = id => { if (!nodes.has(id)) nodes.set(id,{value:'',textContent:'',innerHTML:'',disabled:false}); return nodes.get(id); };
const context = {$,escapeHtml:s=>String(s),metric:v=>v==null?'-':`${v}%`};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('let myCandidates ='),source.indexOf('async function loadMyCandidates')),context);
context.items=Array.from({length:100},(_,i)=>({symbol:String(i).padStart(6,'0'),name:`기업${i}`,market:'KOSPI',analysis:i%2?null:{rank:'A',overall_score:80,generated_at:'2026-10-01'}}));
const run=s=>vm.runInContext(s,context);
run('renderMyCandidates(items)');
assert.equal($('#my-long-term-count').textContent,100);
assert.equal($('#my-watch-page').textContent,'1 / 10');
assert.equal(($('#my-long-term-candidates').innerHTML.match(/<tr>/g)||[]).length,10);
run('myPage=10;renderMyCandidates(items)');
assert.equal($('#my-watch-next').disabled,true);
assert.ok($('#my-long-term-candidates').innerHTML.includes('기업99'));
run('renderMyCandidates(items)');assert.equal($('#my-watch-page').textContent,'10 / 10');
$('#my-watch-rank').value='pending';run('myPage=1;renderMyCandidates(items)');assert.equal($('#my-watch-page').textContent,'1 / 5');
$('#my-watch-query').value='000099';run('renderMyCandidates(items)');assert.ok($('#my-long-term-candidates').innerHTML.includes('기업99'));
$('#my-watch-rank').value='A';run('renderMyCandidates(items)');assert.ok($('#my-long-term-candidates').innerHTML.includes('검색 조건'));
$('#my-watch-query').value='';$('#my-watch-rank').value='';run('myPage=10;renderMyCandidates(items.slice(0,7))');assert.equal($('#my-watch-page').textContent,'1 / 1');
run('renderMyCandidates([])');assert.ok($('#my-long-term-candidates').innerHTML.includes('관찰할 기업을 추가'));
console.log('Watchlist checks passed: 100 items, 10 pages, filters, refresh retention, shrinking and empty results.');
