const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('auto_trader/static/app.js', 'utf8');
const context = {};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function paperStatusGuide('), source.indexOf('function renderDataSummary(')), context);
const guide = (strategy, workspace={}, risk={}) => context.paperStatusGuide(strategy, workspace, risk);
assert.equal(guide({running:false,data_message:'운영 시간 외 대기'}).label,'전략 정지');
assert.ok(guide({running:false},{selected_strategy_id:17,snapshot_ready:true}).next.includes('전략 시작'));
assert.equal(guide({running:false,emergency_stopped:true}).label,'긴급 정지');
assert.equal(guide({running:true,data_message:'운영 시간 외 대기'}).label,'운영 시간 대기');
assert.equal(guide({running:true,data_message:'시세 오류·지연 또는 휴장'}).label,'시세 대기');
assert.equal(guide({running:true,data_message:'0/10종목 판단 가능 · 대기'}).label,'시세 대기');
assert.equal(guide({running:true,data_message:'7/10종목 판단 가능 · 대기'}).label,'일부 종목 시세 대기');
const blocked=guide({running:true,data_message:'실제 현재가 · 완료된 1분봉 · 모의 체결'}, {}, {new_buys_allowed:false,block_reason:'일일 손실 한도'});
assert.equal(blocked.reason,'일일 손실 한도');
assert.ok(blocked.next.includes('청산 감시'));
assert.equal(guide({running:true,data_message:'실제 현재가 · 완료된 1분봉 · 모의 체결'}).label,'정상 감시 중');
assert.equal(guide({running:true,operating_state:'WEEKEND'}).label,'주말 대기');
assert.equal(guide({running:false,operating_state:'WEEKEND'}).label,'전략 정지');
assert.equal(guide({running:true,operating_state:'OUTSIDE_HOURS'}).label,'운영 시간 대기');
assert.equal(guide({running:true,operating_state:'HOLIDAY'}).label,'휴장일 대기');
assert.equal(guide({running:true,operating_state:'MARKET_CLOSED'}).label,'거래 시간 대기');
assert.equal(guide({running:true,operating_state:'MARKET_UNKNOWN'}).label,'거래 시간 확인 대기');
assert.ok(guide({running:true,operating_state:'HOLIDAY',market_next_open_at:'2026-10-05T08:00:00+09:00'}).next.includes('설정 운영 시간'));
assert.equal(guide({running:false,operating_state:'MARKET_UNKNOWN'}).label,'전략 정지');
assert.equal(guide({running:true,data_message:'API 요청 한도 대기: 다음 조회'}).label,'API 요청 한도 대기');
assert.equal(guide({running:true,last_data_at:'2026-10-03T10:00:00+09:00',checked_at:'2026-10-03T10:02:00+09:00'}).label,'시세 지연');
assert.equal(guide({running:true,operating_state:'WEEKEND',last_data_at:'2026-10-03T10:00:00+09:00',checked_at:'2026-10-03T10:02:00+09:00'}).label,'주말 대기');
assert.ok(guide({running:true}).next.includes('추가 확인'));
console.log('PAPER status: stop precedence, preparation, hours, API wait, partial feed and buy-only limits passed.');
const nodes=new Map();
context.$=selector=>{if(!nodes.has(selector))nodes.set(selector,{textContent:'',innerHTML:'',dataset:{},querySelector(){return null;}});return nodes.get(selector);};
context.escapeHtml=value=>String(value);
context.recentSnapshots=()=>[];
vm.runInContext(source.slice(source.indexOf('function renderDataSummary('),source.indexOf('function renderStrategyReturn(')),context);
context.renderDataSummary({running:false,last_data_at:'2026-10-03T01:02:03Z',last_decision_at:'2026-10-03T01:01:00Z'});
assert.ok(nodes.get('#paper-last-data').textContent.includes('10:02:03'));
assert.ok(nodes.get('#paper-last-decision').textContent.includes('10:01:00'));
assert.equal(nodes.get('#strategy-pill').textContent,'전략 정지');
context.renderDataSummary({running:true,operating_state:'WEEKEND'});
assert.equal(nodes.get('#paper-last-data').textContent,'수신 전');
assert.equal(nodes.get('#paper-last-decision').textContent,'확인 전');
assert.equal(nodes.get('#paper-operation-label').textContent,'주말 대기');
console.log('PAPER status rendering: Korean time, stop label, weekend and account/strategy timestamp reset passed.');
