const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={Intl,Date,Number,document:{querySelectorAll:()=>[]},AssetPrivacy:{onChange(){}}};vm.createContext(context);
vm.runInContext(fs.readFileSync('auto_trader/static/live-assets.js','utf8'),context);
const data={portfolio:{holdings:[{name:'A',symbol:'1',market_value:75},{name:'B',symbol:'2',market_value:25}]},buying_power:{krw_cash_buying_power:100},history:[{at:'2026-10-01T00:00:00Z',total_assets:200},{at:'2026-09-01T00:00:00Z',total_assets:100},{at:'2026-10-02T00:00:00Z',total_assets:'NaN'}]};
context.data=data;
const shares=vm.runInContext('LiveAssets.allocationRows(data)',context);
assert.equal(shares[0].name,'원화 주문 가능');assert.equal(shares[0].share,50);assert.equal(shares.reduce((n,r)=>n+r.share,0),100);
context.now=Date.parse('2026-10-03T00:00:00Z');const history=vm.runInContext('LiveAssets.historyPoints(data,7,now)',context);
assert.equal(history.length,1);assert.equal(history[0].total_assets,200);
context.empty={portfolio:{holdings:[]},buying_power:{krw_cash_buying_power:0},history:[]};
assert.equal(vm.runInContext('LiveAssets.allocationRows(empty)[0].share',context),0);
assert.equal(vm.runInContext('LiveAssets.historyPoints(empty,30,now).length',context),0);
const nodes=new Map();const element=()=>({dataset:{},style:{},classList:{add(){},remove(){}},textContent:'',innerHTML:'',replaceChildren(){this.textContent='';this.innerHTML='';},append(){}});
context.document.getElementById=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};context.document.createElement=element;
context.AssetPrivacy.hidden=()=>false;
vm.runInContext('LiveAssets.update(empty)',context);assert.ok(nodes.get('live-asset-chart').textContent.includes('없습니다'));
context.single={...data,history:[{at:new Date().toISOString(),total_assets:200}]};
vm.runInContext('LiveAssets.update(single)',context);assert.ok(nodes.get('live-asset-chart').textContent.includes('수집을 시작'));assert.equal(nodes.get('live-asset-chart').innerHTML,'');
context.AssetPrivacy.hidden=()=>true;vm.runInContext('LiveAssets.update(single)',context);assert.ok(nodes.get('live-asset-chart').textContent.includes('가려져'));assert.ok(nodes.get('live-allocation').textContent.includes('가려져'));
console.log('Live assets: allocation totals, zero assets, period cutoff, invalid history filtering passed.');
